debug: false
management.endpoints.web.exposure.include: "*" # -> Actuator의 가려진 부분 보기

logging:
  level:
    com.project.projectb: debug
    org.springframework.web.servlet: debug # -> request, response의 Log 보기
    org.hibernate.type.descriptor.sql.BasicBinder: trace # -> JPA를 쓸뗴 Query 로그를 출력
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: BLoHny
    password: ird1600215!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # -> 테스트용 database 데이터 생성
    hibernate.ddl-auto: create # -> 자동 Article, Article comment 생성
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # -> 10개의 쿼리를 하나의 SELECT문으로 설정
  h2.console.enabled: true
  sql.init.mode: always